### ISSUE TITLE
Look at packaging options

### ISSUE THREAD

**Issue by robertdfrench** [robertdfrench/khef#11]
* pip
* pyoxidzer

**Comment by robertdfrench** [comment]
I'm thinking about this more, and I really don't want to do any packaging. It is a giant can of worms (philosophically). This program is a single, plaintext python file for the sole purpose of making it easy to audit. Anyone not trying to audit their shared keychain program is not the target audience. At least, this is my thinking on the matter.

**Comment by robertdfrench** [comment]
Yep, getting rid of this. Feel free to push back if you think I'm going off the rails @AnthonyDiGirolamo

**Comment by AnthonyDiGirolamo** [comment]
Sounds good to me!
