### ISSUE TITLE
What does the 100% code coverage requirement mean across platforms?

### ISSUE THREAD

**Issue by robertdfrench** [robertdfrench/khef#14]
If we write macOS-specific code (integration with `security` tool) it will not run correctly when tested on Linux. So maybe some region of platform-specific stuff will have to be introduced where the coverage requirements are relaxed, or something. Need to puzzle this out, or dig around for prior art.

**Comment by robertdfrench** [comment]
As of right now I'm thinking, just punt on #10 and only support macOS.

**Comment by robertdfrench** [comment]
Maybe something like https://coverage.readthedocs.io/en/stable/excluding.html#advanced-exclusion and have a config file look for different exclude pragmas on different platforms? So a block could be `#pragma: macos only` and would be excluded on other platforms, but that would require dynamically generating a config file for coverage.py, which seems sortof gross.

**Comment by AnthonyDiGirolamo** [comment]
I am interested in making this work for gnome-keyring via the `secret-tool`
command line app.

Maybe you can have tests for it running on MacOS too. It's in pkgsrc
https://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/security/gnome-keyring/index.html
https://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/security/libsecret/index.html

That would let you keep 100% code coverage on Mac
