### ISSUE TITLE
Support for Sombra Corp's "Windows" Platform

### ISSUE THREAD

**Issue by robertdfrench** [robertdfrench/khef#18]
I think the trick here may be to check for and install this powershell module -- https://github.com/powershell/SecretManagement

I believe (but have not confirmed) that the github.com/powershell organization is a legit Microsoft org.

I do not want users to have to install 3rd party dependencies for `khef`, but if the 3rd party is your OS vendor, maybe that's okay.

**Comment by robertdfrench** [comment]
I have no personal interest in this. If neither of you do either, we can just close it.

**Comment by robertdfrench** [comment]
@AnthonyDiGirolamo is this the tool you were trying to use? https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/cc754243(v=ws.11)

**Comment by AnthonyDiGirolamo** [comment]
That's the one I tried yeah. For now I'll focus my efforts on gnome-keyring.

**Comment by robertdfrench** [comment]
This is too bizarre, closing for the time being. More than willing to take another look.
